const express = require('express')
const cors = require('cors')
const bcrypt = require('bcryptjs')
const jwt = require('jsonwebtoken')
const { createClient } = require('@supabase/supabase-js')

const app = express()
app.use(cors())
app.use(express.json({ limit: '50mb' }))

const supabase = createClient(
  process.env.SUPABASE_URL || '',
  process.env.SUPABASE_KEY || ''
)
const JWT_SECRET = 'oms-prestair-secret-key-2026'

function generateToken(user) {
  return jwt.sign({ id: user.id, username: user.username, role: user.role }, JWT_SECRET, { expiresIn: '24h' })
}
async function authenticate(req, res, next) {
  const h = req.headers.authorization
  if (!h || !h.startsWith('Bearer ')) return res.status(401).json({ error: 'Unauthorized' })
  try {
    const decoded = jwt.verify(h.split(' ')[1], JWT_SECRET)
    req.user = decoded
    // Check force logout
    const { data: userData } = await supabase.from('users').select('force_logout_at').eq('id', decoded.id)
    if (userData?.[0]?.force_logout_at) {
      const logoutTime = new Date(userData[0].force_logout_at).getTime() / 1000
      if (decoded.iat && logoutTime > decoded.iat) return res.status(401).json({ error: 'Session expired. Please login again.' })
    }
    next()
  } catch (e) { return res.status(401).json({ error: 'Invalid token' }) }
}
function adminOnly(req, res, next) {
  if (req.user.role !== 'admin') return res.status(403).json({ error: 'Admin only' })
  next()
}
function mapOrder(o) {
  if (!o) return o
  const totalAmt = parseFloat(o.total_amount) || 0
  const receivedAmt = parseFloat(o.received_amount) || 0
  const balance = totalAmt - receivedAmt
  const percentReceived = totalAmt ? parseFloat(((receivedAmt / totalAmt) * 100).toFixed(2)) : 0
  return { id: o.id, date: o.date, poNo: o.po_no, client: o.client, orderNo: o.order_no, status: o.status, deliveryDate: o.delivery_date, deliveryRemarks: o.delivery_remarks, customerName: o.customer_name, gst: o.gst, billingAddress: o.billing_address, followUp: o.follow_up, salesRep: o.sales_rep, deliveryAddress: o.delivery_address, phoneNo: o.phone_no, siteVerification: o.site_verification, siteVerificationRemarks: o.site_verification_remarks, installationStatus: o.installation_status, installationRemarks: o.installation_remarks, lop: o.lop, sectionDrawing: o.section_drawing, sectionDrawingRemarks: o.section_drawing_remarks, inProduction: o.in_production, billing: o.billing, installation: o.installation, totalAmount: totalAmt, receivedAmount: receivedAmt, balance: balance, percentReceived: percentReceived, paymentRemarks: o.payment_remarks, paymentProofUrl: o.payment_proof_url, daysToOrder: o.days_to_order, remarks: o.remarks, akhilSirAudit: o.akhil_sir_audit, advanceBill: o.advance_bill, orRecvd: o.or_recvd, photography: o.photography, photographyRemarks: o.photography_remarks, siteVideo: o.site_video, siteVideoRemarks: o.site_video_remarks, review: o.review, reviewRemarks: o.review_remarks, rowColor: o.row_color || '', createdAt: o.created_at }
}
function snakeOrder(o) {
  if (!o) return o; const s = {}
  if (o.date !== undefined) s.date = o.date; if (o.poNo !== undefined) s.po_no = o.poNo; if (o.client !== undefined) s.client = o.client; if (o.orderNo !== undefined) s.order_no = o.orderNo; if (o.status !== undefined) s.status = o.status; if (o.deliveryDate !== undefined) s.delivery_date = o.deliveryDate; if (o.customerName !== undefined) s.customer_name = o.customerName; if (o.gst !== undefined) s.gst = o.gst; if (o.totalAmount !== undefined) s.total_amount = parseFloat(o.totalAmount) || 0; if (o.receivedAmount !== undefined) s.received_amount = parseFloat(o.receivedAmount) || 0; if (o.balance !== undefined) s.balance = parseFloat(o.balance) || 0; if (o.photography !== undefined) s.photography = o.photography; if (o.photographyRemarks !== undefined) s.photography_remarks = o.photographyRemarks; if (o.siteVideo !== undefined) s.site_video = o.siteVideo; if (o.siteVideoRemarks !== undefined) s.site_video_remarks = o.siteVideoRemarks; if (o.review !== undefined) s.review = o.review; if (o.reviewRemarks !== undefined) s.review_remarks = o.reviewRemarks; if (o.orRecvd !== undefined) s.or_recvd = o.orRecvd; if (o.billingAddress !== undefined) s.billing_address = o.billingAddress; if (o.deliveryAddress !== undefined) s.delivery_address = o.deliveryAddress; if (o.phoneNo !== undefined) s.phone_no = o.phoneNo; if (o.salesRep !== undefined) s.sales_rep = o.salesRep; if (o.followUp !== undefined) s.follow_up = o.followUp; if (o.deliveryRemarks !== undefined) s.delivery_remarks = o.deliveryRemarks; if (o.siteVerification !== undefined) s.site_verification = o.siteVerification; if (o.siteVerificationRemarks !== undefined) s.site_verification_remarks = o.siteVerificationRemarks; if (o.installationStatus !== undefined) s.installation_status = o.installationStatus; if (o.installationRemarks !== undefined) s.installation_remarks = o.installationRemarks; if (o.lop !== undefined) s.lop = o.lop; if (o.sectionDrawing !== undefined) s.section_drawing = o.sectionDrawing; if (o.sectionDrawingRemarks !== undefined) s.section_drawing_remarks = o.sectionDrawingRemarks; if (o.inProduction !== undefined) s.in_production = o.inProduction; if (o.billing !== undefined) s.billing = o.billing; if (o.installation !== undefined) s.installation = o.installation; if (o.remarks !== undefined) s.remarks = o.remarks; if (o.akhilSirAudit !== undefined) s.akhil_sir_audit = o.akhilSirAudit; if (o.advanceBill !== undefined) s.advance_bill = o.advanceBill; if (o.paymentRemarks !== undefined) s.payment_remarks = o.paymentRemarks; if (o.paymentProofUrl !== undefined) s.payment_proof_url = o.paymentProofUrl; if (o.rowColor !== undefined) s.row_color = o.rowColor
  return s
}

// AUTH
app.post('/api/auth/login', async (req, res) => {
  try {
    const { username, password } = req.body
    const { data: users } = await supabase.from('users').select('*').ilike('username', username)
    const user = users?.[0]
    if (!user) return res.status(401).json({ error: 'Invalid credentials' })
    const valid = bcrypt.compareSync(password.toLowerCase(), user.password)
    if (!valid) return res.status(401).json({ error: 'Invalid credentials' })
    const token = generateToken({ id: user.id, username: user.username, role: user.role })
    let userGroup = null
    if (user.user_group) { const { data: g } = await supabase.from('groups').select('*').eq('name', user.user_group); userGroup = g?.[0] }
    const mergedPerms = { ...(userGroup?.column_permissions || {}), ...(user.column_permissions || {}) }
    const gr = (k) => { if (user[k] === true || user[k] === false) return user[k]; if (userGroup && (userGroup[k] === true || userGroup[k] === false)) return userGroup[k]; return false }
    const isAdmin = user.role === 'admin'
    res.json({ token, user: { id: user.id, username: user.username, fullName: user.full_name, role: user.role, group: user.user_group || '', columnPermissions: isAdmin ? {} : mergedPerms, canEdit: isAdmin || gr('can_edit'), canReceipt: isAdmin || gr('can_receipt'), canAssignReminder: isAdmin || gr('can_assign_reminder'), canDelete: isAdmin || gr('can_delete'), canCreateQuote: isAdmin || gr('can_create_quote'), canColor: isAdmin || gr('can_color') } })
  } catch (e) { res.status(500).json({ error: e.message }) }
})
app.post('/api/auth/change-password', authenticate, async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body
    const { data: users } = await supabase.from('users').select('*').eq('id', req.user.id)
    if (!users?.[0]) return res.status(404).json({ error: 'Not found' })
    if (!bcrypt.compareSync(currentPassword.toLowerCase(), users[0].password)) return res.status(400).json({ error: 'Wrong password' })
    await supabase.from('users').update({ password: bcrypt.hashSync(newPassword.toLowerCase(), 10) }).eq('id', req.user.id)
    res.json({ message: 'Changed' })
  } catch (e) { res.status(500).json({ error: e.message }) }
})

// USERS
app.get('/api/users/list', authenticate, async (req, res) => { try { const { data } = await supabase.from('users').select('id, username, full_name, role'); res.json((data||[]).map(u=>({id:u.id,username:u.username,fullName:u.full_name,full_name:u.full_name,role:u.role}))) } catch (e) { res.status(500).json({ error: e.message }) } })
app.get('/api/users/groups', authenticate, async (req, res) => { try { const { data } = await supabase.from('groups').select('*'); res.json(data || []) } catch (e) { res.status(500).json({ error: e.message }) } })
app.get('/api/users', authenticate, adminOnly, async (req, res) => { try { const { data } = await supabase.from('users').select('id,username,full_name,role,user_group,column_permissions,can_edit,can_receipt,can_assign_reminder,can_delete,can_create_quote,can_color,plain_password'); res.json((data||[]).map(u=>({...u,fullName:u.full_name,group:u.user_group,columnPermissions:u.column_permissions,canEdit:u.can_edit,canReceipt:u.can_receipt,canAssignReminder:u.can_assign_reminder,canDelete:u.can_delete,canCreateQuote:u.can_create_quote,canColor:u.can_color,plainPassword:u.plain_password}))) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/users', authenticate, adminOnly, async (req, res) => { try { const {username,password,fullName,role,group,columnPermissions,canEdit,canReceipt,canAssignReminder,canDelete,canCreateQuote}=req.body; const{data,error}=await supabase.from('users').insert({username,password:bcrypt.hashSync(password.toLowerCase(),10),plain_password:password.toLowerCase(),full_name:fullName,role:role||'user',user_group:group||'',column_permissions:columnPermissions||{},can_edit:canEdit||false,can_receipt:canReceipt||false,can_assign_reminder:canAssignReminder||false,can_delete:canDelete||false,can_create_quote:canCreateQuote||false,can_color:req.body.canColor||false}).select(); if(error)return res.status(400).json({error:error.message}); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/users/:id', authenticate, adminOnly, async (req, res) => { try { const{fullName,role,group,columnPermissions,canEdit,canReceipt,canAssignReminder,canDelete,canCreateQuote}=req.body; await supabase.from('users').update({full_name:fullName,role,user_group:group||'',column_permissions:columnPermissions||{},can_edit:canEdit||false,can_receipt:canReceipt||false,can_assign_reminder:canAssignReminder||false,can_delete:canDelete||false,can_create_quote:canCreateQuote||false,can_color:req.body.canColor||false}).eq('id',parseInt(req.params.id)); res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/users/:id/password', authenticate, adminOnly, async (req, res) => { try { const{newPassword}=req.body; await supabase.from('users').update({password:bcrypt.hashSync(newPassword.toLowerCase(),10),plain_password:newPassword.toLowerCase()}).eq('id',parseInt(req.params.id)); res.json({message:'Password reset'}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/users/:id', authenticate, adminOnly, async (req, res) => { try { if(parseInt(req.params.id)===req.user.id)return res.status(400).json({error:'Cannot delete yourself'}); await supabase.from('users').delete().eq('id',parseInt(req.params.id)); res.json({message:'User deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/users/:id/force-logout', authenticate, adminOnly, async (req, res) => { try { await supabase.from('users').update({force_logout_at:new Date().toISOString()}).eq('id',parseInt(req.params.id)); res.json({message:'User forced to logout'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/users/groups', authenticate, adminOnly, async (req, res) => { try { const{name,column_permissions,can_edit,can_receipt,can_assign_reminder,can_delete,can_create_quote}=req.body; const{data,error}=await supabase.from('groups').insert({name:(name||'').toUpperCase(),column_permissions:column_permissions||{},can_edit:can_edit||false,can_receipt:can_receipt||false,can_assign_reminder:can_assign_reminder||false,can_delete:can_delete||false,can_create_quote:can_create_quote||false}).select(); if(error)return res.status(400).json({error:error.message}); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/users/groups/:id', authenticate, adminOnly, async (req, res) => { try { const{name,column_permissions,can_edit,can_receipt,can_assign_reminder,can_delete,can_create_quote}=req.body; await supabase.from('groups').update({name:(name||'').toUpperCase(),column_permissions:column_permissions||{},can_edit:can_edit||false,can_receipt:can_receipt||false,can_assign_reminder:can_assign_reminder||false,can_delete:can_delete||false,can_create_quote:can_create_quote||false}).eq('id',parseInt(req.params.id)); res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/users/groups/:id', authenticate, adminOnly, async (req, res) => { try { await supabase.from('groups').delete().eq('id',parseInt(req.params.id)); res.json({message:'Group deleted'}) } catch(e){res.status(500).json({error:e.message})} })

// ORDERS
app.get('/api/orders', authenticate, async (req, res) => { try { const{data}=await supabase.from('orders').select('*'); const mapped=(data||[]).map(o=>mapOrder(o)); const getOrderParts=(orderNo)=>{if(!orderNo)return{fy:0,num:0};const parts=orderNo.split('/');let fy=0;let num=0;if(parts.length>=3){const fyDigits=parts[1].match(/^(\d{4})/);if(fyDigits)fy=parseInt(fyDigits[1]);const numDigits=parts[2].match(/^(\d+)/);if(numDigits)num=parseInt(numDigits[1])}return{fy,num}}; mapped.sort((a,b)=>{const pa=getOrderParts(a.orderNo);const pb=getOrderParts(b.orderNo);if(pb.fy!==pa.fy)return pb.fy-pa.fy;return pb.num-pa.num}); res.json(mapped) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/deleted/all', authenticate, async (req, res) => { try { const{data}=await supabase.from('deleted_orders').select('*'); const getOrderParts=(orderNo)=>{if(!orderNo)return{fy:0,num:0};const parts=orderNo.split('/');let fy=0;let num=0;if(parts.length>=3){const fyDigits=parts[1].match(/^(\d{4})/);if(fyDigits)fy=parseInt(fyDigits[1]);const numDigits=parts[2].match(/^(\d+)/);if(numDigits)num=parseInt(numDigits[1])}return{fy,num}}; const mapped=(data||[]).map(d=>({...d.data,id:d.original_id,deletedBy:d.deleted_by,deletedAt:d.deleted_at})); mapped.sort((a,b)=>{const pa=getOrderParts(a.orderNo);const pb=getOrderParts(b.orderNo);if(pb.fy!==pa.fy)return pb.fy-pa.fy;return pb.num-pa.num}); res.json(mapped) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/payments/all', authenticate, async (req, res) => { try { const{data:payments}=await supabase.from('payments').select('*').order('date',{ascending:false}); const{data:allOrders}=await supabase.from('orders').select('id,order_no,client,date,total_amount,received_amount,balance'); const om={};(allOrders||[]).forEach(o=>{om[o.id]=o}); res.json((payments||[]).map(p=>{const o=om[p.order_id]||{};return{id:p.id,orderId:p.order_id,paymentDate:p.date,amount:p.amount,mode:p.mode,remarks:p.remarks,orderNo:o.order_no||'',client:o.client||'',orderDate:o.date||'',totalAmount:o.total_amount||0,receivedAmount:o.received_amount||0,balance:o.balance||0}})) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/reminders/due', authenticate, async (req, res) => { try { const{data}=await supabase.from('reminders').select('*'); const filtered=(data||[]).filter(r=>{if(r.responded_by)return false; if(req.user.role==='admin')return true;if(r.created_by===req.user.username)return true;if(r.visible_to&&r.visible_to.includes(req.user.username))return true;return false}); res.json(filtered.map(r=>({...r,orderNo:r.order_no,createdBy:r.created_by,orderId:r.order_id,visibleTo:r.visible_to,responseText:r.response_text}))) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/app-version', async (req, res) => { try { const{data}=await supabase.from('app_settings').select('value').eq('key','app_version').order('id',{ascending:false}).limit(1); res.json({version:data?.[0]?.value||'1'}) } catch(e){res.json({version:'1'})} })
app.post('/api/force-refresh', authenticate, adminOnly, async (req, res) => { try { const newVersion=Date.now().toString(); const{data:existing}=await supabase.from('app_settings').select('*').eq('key','app_version'); if(existing&&existing.length>0){await supabase.from('app_settings').update({value:newVersion}).eq('key','app_version'); if(existing.length>1){const keepId=existing[0].id; for(let i=1;i<existing.length;i++){await supabase.from('app_settings').delete().eq('id',existing[i].id)}}}else{await supabase.from('app_settings').insert({key:'app_version',value:newVersion})} res.json({message:'Force refresh triggered',version:newVersion}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/orders/reminders/:id', authenticate, async (req, res) => { try { await supabase.from('reminders').delete().eq('id',parseInt(req.params.id)); res.json({message:'Dismissed'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/reminders/:id/respond', authenticate, async (req, res) => { try { const{responseText}=req.body; if(!responseText||responseText.trim().length<10)return res.status(400).json({error:'Response must be at least 10 characters'}); if(responseText.trim().length>250)return res.status(400).json({error:'Response must not exceed 250 characters'}); const{data:existing}=await supabase.from('reminders').select('response_text').eq('id',parseInt(req.params.id)); const prev=existing?.[0]?.response_text||''; const dateStr=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'2-digit',year:'2-digit'}); const newResponse=prev?`${prev} | ${dateStr}: ${responseText.toUpperCase()}`:`${dateStr}: ${responseText.toUpperCase()}`; await supabase.from('reminders').update({response_text:newResponse,response_date:new Date().toISOString(),responded_by:req.user.username}).eq('id',parseInt(req.params.id)); res.json({message:'Response saved'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/reminders/:id/reassign', authenticate, async (req, res) => { try { const{reason}=req.body; const{data:existing}=await supabase.from('reminders').select('response_text').eq('id',parseInt(req.params.id)); const prev=existing?.[0]?.response_text||''; const dateStr=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'2-digit',year:'2-digit'}); const reasonText=reason?` - ${reason}`:'' ; const appendText=`${prev?prev+' | ':''}${dateStr}: REASSIGNED BY ${req.user.username.toUpperCase()}${reasonText}`; await supabase.from('reminders').update({response_text:appendText,response_date:null,responded_by:null,date:new Date().toISOString().split('T')[0]}).eq('id',parseInt(req.params.id)); res.json({message:'Reminder reassigned'}) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/reminders/all', authenticate, async (req, res) => { try { const{data}=await supabase.from('reminders').select('*').order('created_at',{ascending:false}); const isAdmin=req.user.role==='admin'; const filtered=(data||[]).filter(r=>{if(isAdmin)return true;return r.created_by===req.user.username}); res.json(filtered.map(r=>({...r,orderNo:r.order_no,createdBy:r.created_by,orderId:r.order_id,visibleTo:r.visible_to,assignedTo:r.assigned_to,responseText:r.response_text,responseDate:r.response_date,respondedBy:r.responded_by}))) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/paper-requests/all', authenticate, async (req, res) => { try { const{data}=await supabase.from('paper_requests').select('*').order('id',{ascending:false}); res.json((data||[]).map(r=>({...r,orderNo:r.order_no,requestedBy:r.requested_by,issueTo:r.issue_to,acceptedBy:r.accepted_by,acceptedAt:r.accepted_at,rejectRemarks:r.reject_remarks,createdAt:r.created_at}))) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/paper-requests/my', authenticate, async (req, res) => { try { const{data}=await supabase.from('paper_requests').select('*').eq('issue_to',req.user.username).eq('status','PENDING'); res.json((data||[]).map(r=>({...r,orderNo:r.order_no,requestedBy:r.requested_by,issueTo:r.issue_to}))) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/paper-requests', authenticate, async (req, res) => { try { const{orderNo,issueTo}=req.body; if(!orderNo||!issueTo)return res.status(400).json({error:'Order No and Issue To required'}); const{data:pendingReqs}=await supabase.from('paper_requests').select('*').eq('order_no',orderNo).eq('status','PENDING'); if(pendingReqs&&pendingReqs.length>0){const pendingWith=pendingReqs[0].issue_to;return res.status(400).json({error:`Order ${orderNo} is already pending with ${pendingWith.toUpperCase()}`})} const{data:acceptedReqs}=await supabase.from('paper_requests').select('*').eq('order_no',orderNo).eq('status','ACCEPTED'); if(acceptedReqs&&acceptedReqs.length>0){const{data:returnAccepted}=await supabase.from('return_requests').select('*').eq('order_no',orderNo).eq('status','ACCEPTED');if(!returnAccepted||returnAccepted.length===0){const issuedTo=acceptedReqs[0].requested_by||acceptedReqs[0].issue_to;return res.status(400).json({error:`Order ${orderNo} is already issued to ${issuedTo.toUpperCase()} (not returned yet)`,issuedTo:issuedTo,canReissue:true})}} const{data:orders}=await supabase.from('orders').select('client').eq('order_no',orderNo); const client=orders?.[0]?.client||''; const{data,error}=await supabase.from('paper_requests').insert({order_no:orderNo,client,requested_by:req.user.username,issue_to:issueTo,status:'PENDING'}).select(); if(error)return res.status(400).json({error:error.message}); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/paper-requests/:id/accept', authenticate, async (req, res) => { try { const{data:reqs}=await supabase.from('paper_requests').select('*').eq('id',parseInt(req.params.id)); if(!reqs?.length)return res.status(404).json({error:'Not found'}); const request=reqs[0]; if(request.reject_remarks==='REISSUE'){await supabase.from('paper_requests').update({status:`REISSUED TO ${request.requested_by.toUpperCase()}`}).eq('order_no',request.order_no).eq('status','ACCEPTED'); await supabase.from('paper_requests').update({status:'ACCEPTED',accepted_by:req.user.username,accepted_at:new Date().toISOString(),reject_remarks:`REISSUE BY ${req.user.username.toUpperCase()}`}).eq('id',request.id)}else{await supabase.from('paper_requests').update({status:'ACCEPTED',accepted_by:req.user.username,accepted_at:new Date().toISOString()}).eq('id',parseInt(req.params.id))} res.json({message:'Accepted'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/paper-requests/reissue', authenticate, async (req, res) => { try { const{orderNo}=req.body; if(!orderNo)return res.status(400).json({error:'Order No required'}); const{data:allReqs}=await supabase.from('paper_requests').select('status').eq('order_no',orderNo); const reissueCount=(allReqs||[]).filter(r=>r.status&&r.status.startsWith('REISSUED')).length; if(reissueCount>=2)return res.status(400).json({error:'Maximum 2 reissues reached. Please use Return Request.'}); const{data:acceptedReqs}=await supabase.from('paper_requests').select('*').eq('order_no',orderNo).eq('status','ACCEPTED'); if(!acceptedReqs||acceptedReqs.length===0)return res.status(400).json({error:'No active issue found'}); const currentHolder=acceptedReqs[0].requested_by||acceptedReqs[0].issue_to; const{data:orders}=await supabase.from('orders').select('client').eq('order_no',orderNo); const client=orders?.[0]?.client||''; const{data,error}=await supabase.from('paper_requests').insert({order_no:orderNo,client,requested_by:req.user.username,issue_to:currentHolder,status:'PENDING',reject_remarks:'REISSUE'}).select(); if(error)return res.status(400).json({error:error.message}); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/paper-requests/:id/reject', authenticate, async (req, res) => { try { const{remarks}=req.body; await supabase.from('paper_requests').update({status:`REJECTED: ${remarks||''}`,rejected_by:req.user.username,reject_remarks:remarks||''}).eq('id',parseInt(req.params.id)); res.json({message:'Rejected'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/paper-requests/:id/change-user', authenticate, async (req, res) => { try { const{issueTo}=req.body; const{data:reqs}=await supabase.from('paper_requests').select('*').eq('id',parseInt(req.params.id)); if(!reqs?.length)return res.status(404).json({error:'Not found'}); if(reqs[0].requested_by!==req.user.username&&req.user.role!=='admin')return res.status(403).json({error:'Only requester can change'}); if(reqs[0].status!=='PENDING')return res.status(400).json({error:'Can only change before acceptance'}); await supabase.from('paper_requests').update({issue_to:issueTo}).eq('id',parseInt(req.params.id)); res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/return-requests/:id/change-user', authenticate, async (req, res) => { try { const{returnTo}=req.body; const{data:reqs}=await supabase.from('return_requests').select('*').eq('id',parseInt(req.params.id)); if(!reqs?.length)return res.status(404).json({error:'Not found'}); if(reqs[0].requested_by!==req.user.username&&req.user.role!=='admin')return res.status(403).json({error:'Only requester can change'}); if(reqs[0].status!=='PENDING')return res.status(400).json({error:'Can only change before acceptance'}); await supabase.from('return_requests').update({return_to:returnTo}).eq('id',parseInt(req.params.id)); res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/paper-requests/:id/reroute', authenticate, async (req, res) => { try { const{rerouteTo}=req.body; const{data:reqs}=await supabase.from('paper_requests').select('*').eq('id',parseInt(req.params.id)); if(!reqs?.length)return res.status(404).json({error:'Not found'}); const r=reqs[0]; await supabase.from('paper_requests').update({status:`REROUTED TO ${rerouteTo.toUpperCase()}`,rerouted_by:req.user.username}).eq('id',r.id); const{data}=await supabase.from('paper_requests').insert({order_no:r.order_no,client:r.client,requested_by:r.requested_by,issue_to:rerouteTo,status:'PENDING'}).select(); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/orders/paper-requests/:id', authenticate, adminOnly, async (req, res) => { try { await supabase.from('paper_requests').delete().eq('id',parseInt(req.params.id)); res.json({message:'Deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/return-requests/all', authenticate, async (req, res) => { try { const{data}=await supabase.from('return_requests').select('*').order('id',{ascending:false}); res.json((data||[]).map(r=>({...r,orderNo:r.order_no,requestedBy:r.requested_by,returnTo:r.return_to,acceptedBy:r.accepted_by,acceptedAt:r.accepted_at}))) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/return-requests/my', authenticate, async (req, res) => { try { const{data}=await supabase.from('return_requests').select('*').eq('return_to',req.user.username).eq('status','PENDING'); res.json((data||[]).map(r=>({...r,orderNo:r.order_no,requestedBy:r.requested_by,returnTo:r.return_to}))) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/return-requests', authenticate, async (req, res) => { try { const{orderNo,returnTo}=req.body; const{data}=await supabase.from('return_requests').insert({order_no:orderNo,requested_by:req.user.username,return_to:returnTo,status:'PENDING'}).select(); res.json(data[0]) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/return-requests/:id/accept', authenticate, async (req, res) => { try { await supabase.from('return_requests').update({status:'ACCEPTED',accepted_by:req.user.username,accepted_at:new Date().toISOString()}).eq('id',parseInt(req.params.id)); res.json({message:'Accepted'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/return-requests/:id/reject', authenticate, async (req, res) => { try { const{remarks}=req.body; await supabase.from('return_requests').update({status:`REJECTED: ${remarks||''}`,rejected_by:req.user.username,reject_remarks:remarks||''}).eq('id',parseInt(req.params.id)); res.json({message:'Rejected'}) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/:id', authenticate, async (req, res) => { try { const{data}=await supabase.from('orders').select('*').eq('id',parseInt(req.params.id)); if(!data?.length)return res.status(404).json({error:'Not found'}); const{data:payments}=await supabase.from('payments').select('*').eq('order_id',parseInt(req.params.id)); res.json({...mapOrder(data[0]),payments}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders', authenticate, async (req, res) => { try { const{data,error}=await supabase.from('orders').insert(snakeOrder(req.body)).select(); if(error)return res.status(400).json({error:error.message}); res.json(mapOrder(data[0])) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/:id', authenticate, async (req, res) => { try { const AUTO_FIELDS=['receivedAmount','balance','percentReceived','received_amount','percent_received','id','createdAt','created_at','payments','_needsOrderNo','daysToOrder','rowColor','paymentProofUrl','payment_proof_url']; const{data:existing}=await supabase.from('orders').select('*').eq('id',parseInt(req.params.id)); const oldOrder=existing?.[0]?mapOrder(existing[0]):{}; const{error}=await supabase.from('orders').update(snakeOrder(req.body)).eq('id',parseInt(req.params.id)); if(error)return res.status(400).json({error:error.message}); if(req.body.totalAmount!==undefined||req.body.receivedAmount!==undefined){const{data:updated}=await supabase.from('orders').select('total_amount,received_amount').eq('id',parseInt(req.params.id));if(updated?.[0]){const ta=parseFloat(updated[0].total_amount)||0;const ra=parseFloat(updated[0].received_amount)||0;const bal=ta-ra;const pct=ta?parseFloat(((ra/ta)*100).toFixed(2)):0;await supabase.from('orders').update({balance:bal,percent_received:pct}).eq('id',parseInt(req.params.id))}} const changes=[]; Object.keys(req.body).forEach(key=>{if(AUTO_FIELDS.includes(key))return;const oldVal=String(oldOrder[key]||'').trim();const newVal=String(req.body[key]||'').trim();if(oldVal!==newVal&&!(oldVal==='0'&&newVal==='')&&!(oldVal===''&&newVal==='0'))changes.push({field:key,oldValue:oldVal,newValue:newVal})}); if(changes.length>0){await supabase.from('order_edit_history').insert({order_id:parseInt(req.params.id),order_no:oldOrder.orderNo||'',edit_type:'ORDER_EDIT',edited_by:req.user.username,changes})} res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/orders/:id', authenticate, async (req, res) => { try { const{data:orders}=await supabase.from('orders').select('*').eq('id',parseInt(req.params.id)); if(!orders?.length)return res.status(404).json({error:'Not found'}); await supabase.from('deleted_orders').insert({original_id:orders[0].id,data:mapOrder(orders[0]),deleted_by:req.user.username}); await supabase.from('payments').delete().eq('order_id',parseInt(req.params.id)); await supabase.from('orders').delete().eq('id',parseInt(req.params.id)); res.json({message:'Deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/deleted/:id/update', authenticate, adminOnly, async (req, res) => { try { const{data:dels}=await supabase.from('deleted_orders').select('*').eq('original_id',parseInt(req.params.id)); if(!dels?.length)return res.status(404).json({error:'Not found'}); const updatedData={...dels[0].data,...req.body}; const{error}=await supabase.from('deleted_orders').update({data:updatedData}).eq('original_id',parseInt(req.params.id)); if(error)return res.status(400).json({error:error.message}); res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/orders/deleted/:id', authenticate, adminOnly, async (req, res) => { try { await supabase.from('deleted_orders').delete().eq('original_id',parseInt(req.params.id)); res.json({message:'Permanently deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/deleted/:id/restore', authenticate, adminOnly, async (req, res) => { try { const{data:dels}=await supabase.from('deleted_orders').select('*').eq('original_id',parseInt(req.params.id)); if(!dels?.length)return res.status(404).json({error:'Not found'}); const orderData=dels[0].data; const snaked={}; Object.keys(orderData).forEach(k=>{const s=snakeOrder({[k]:orderData[k]}); Object.assign(snaked,s)}); const{error}=await supabase.from('orders').insert(snaked); if(error)return res.status(400).json({error:error.message}); await supabase.from('deleted_orders').delete().eq('original_id',parseInt(req.params.id)); res.json({message:'Restored'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/import', authenticate, adminOnly, async (req, res) => { try { const{orders,overwrite}=req.body;let added=0;const dupes=[]; for(const o of orders){const{data:ex}=await supabase.from('orders').select('id').eq('order_no',o.orderNo);if(ex?.length){if(overwrite){await supabase.from('orders').update(snakeOrder(o)).eq('order_no',o.orderNo);added++}else{dupes.push(o.orderNo)}}else{await supabase.from('orders').insert(snakeOrder(o));added++}} res.json({added,duplicates:dupes}) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/:id/payments', authenticate, async (req, res) => { try { const{data}=await supabase.from('payments').select('*').eq('order_id',parseInt(req.params.id)).order('date',{ascending:false}); res.json(data||[]) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/:id/payments', authenticate, async (req, res) => { try { const{date,mode,amount,remarks}=req.body; await supabase.from('payments').insert({order_id:parseInt(req.params.id),date,mode,amount:parseFloat(amount),remarks}).select(); const{data:pays}=await supabase.from('payments').select('amount').eq('order_id',parseInt(req.params.id)); const tot=(pays||[]).reduce((s,p)=>s+(p.amount||0),0); const{data:ord}=await supabase.from('orders').select('total_amount').eq('id',parseInt(req.params.id)); const ta=ord?.[0]?.total_amount||0; await supabase.from('orders').update({received_amount:tot,balance:ta-tot,percent_received:ta?parseFloat(((tot/ta)*100).toFixed(2)):0}).eq('id',parseInt(req.params.id)); res.json({message:'Added'}) } catch(e){res.status(500).json({error:e.message})} })
app.put('/api/orders/:id/payments/:pid', authenticate, adminOnly, async (req, res) => { try { const{date,mode,amount,remarks}=req.body; const{data:oldPay}=await supabase.from('payments').select('*').eq('id',parseInt(req.params.pid)); const old=oldPay?.[0]||{}; await supabase.from('payments').update({date,mode,amount:parseFloat(amount),remarks}).eq('id',parseInt(req.params.pid)); const{data:pays}=await supabase.from('payments').select('amount').eq('order_id',parseInt(req.params.id)); const tot=(pays||[]).reduce((s,p)=>s+(p.amount||0),0); const{data:ord}=await supabase.from('orders').select('total_amount,order_no').eq('id',parseInt(req.params.id)); const ta=ord?.[0]?.total_amount||0; await supabase.from('orders').update({received_amount:tot,balance:ta-tot,percent_received:ta?parseFloat(((tot/ta)*100).toFixed(2)):0}).eq('id',parseInt(req.params.id)); const changes=[]; if(String(old.date||'')!==String(date||''))changes.push({field:'Receipt Date',oldValue:old.date||'',newValue:date||''}); if(String(old.mode||'')!==String(mode||''))changes.push({field:'Receipt Mode',oldValue:old.mode||'',newValue:mode||''}); if(String(old.amount||'')!==String(amount||''))changes.push({field:'Receipt Amount',oldValue:String(old.amount||''),newValue:String(amount||'')}); if(String(old.remarks||'')!==String(remarks||''))changes.push({field:'Receipt Remarks',oldValue:old.remarks||'',newValue:remarks||''}); if(changes.length>0){await supabase.from('order_edit_history').insert({order_id:parseInt(req.params.id),order_no:ord?.[0]?.order_no||'',edit_type:'RECEIPT_EDIT',edited_by:req.user.username,changes})} res.json({message:'Updated'}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/orders/:id/payments/:pid', authenticate, async (req, res) => { try { await supabase.from('payments').delete().eq('id',parseInt(req.params.pid)); const{data:pays}=await supabase.from('payments').select('amount').eq('order_id',parseInt(req.params.id)); const tot=(pays||[]).reduce((s,p)=>s+(p.amount||0),0); const{data:ord}=await supabase.from('orders').select('total_amount').eq('id',parseInt(req.params.id)); const ta=ord?.[0]?.total_amount||0; await supabase.from('orders').update({received_amount:tot,balance:ta-tot,percent_received:ta?parseFloat(((tot/ta)*100).toFixed(2)):0}).eq('id',parseInt(req.params.id)); res.json({message:'Deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/orders/:id/reminders', authenticate, async (req, res) => { try { const{description,date,visibleTo}=req.body; const{data:orders}=await supabase.from('orders').select('order_no,client').eq('id',parseInt(req.params.id)); const o=orders?.[0]; const users=visibleTo&&visibleTo.length>0?visibleTo:[req.user.username]; const rows=users.map(u=>({order_id:parseInt(req.params.id),order_no:o?.order_no,client:o?.client,description,date,visible_to:[u],assigned_to:u,created_by:req.user.username})); const{data}=await supabase.from('reminders').insert(rows).select(); res.json(data?.[0]||{message:'Reminders created'}) } catch(e){res.status(500).json({error:e.message})} })

app.get('/api/orders/edit-logs/all', authenticate, async (req, res) => { try { const{data}=await supabase.from('order_edit_history').select('*').order('created_at',{ascending:false}).limit(500); res.json(data||[]) } catch(e){res.status(500).json({error:e.message})} })
app.post('/api/upload-payment-proof', authenticate, async (req, res) => { try { const{orderId,fileData,fileName}=req.body; if(!fileData||!fileName)return res.status(400).json({error:'File required'}); const buffer=Buffer.from(fileData,'base64'); if(buffer.length>5*1024*1024)return res.status(400).json({error:'File size must be less than 5MB'}); const ext=(fileName.split('.').pop()||'jpg').toLowerCase(); const allowedExts=['jpg','jpeg','png','gif','webp','pdf']; if(!allowedExts.includes(ext))return res.status(400).json({error:'Only images and PDF allowed'}); const contentTypes={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',pdf:'application/pdf'}; const contentType=contentTypes[ext]||'application/octet-stream'; const safeName=fileName.replace(/[^a-zA-Z0-9._-]/g,'_').substring(0,50); const filePath=`${orderId}/${Date.now()}_${safeName}`; const{error:uploadErr}=await supabase.storage.from('payment-proofs').upload(filePath,buffer,{contentType,upsert:true}); if(uploadErr)return res.status(400).json({error:uploadErr.message}); const{data:urlData}=supabase.storage.from('payment-proofs').getPublicUrl(filePath); const publicUrl=urlData.publicUrl; await supabase.from('orders').update({payment_proof_url:publicUrl}).eq('id',parseInt(orderId)); res.json({url:publicUrl}) } catch(e){res.status(500).json({error:e.message})} })
app.delete('/api/delete-payment-proof/:orderId', authenticate, async (req, res) => { try { const orderId=parseInt(req.params.orderId); const{data:order}=await supabase.from('orders').select('payment_proof_url').eq('id',orderId); const url=order?.[0]?.payment_proof_url; if(url&&url.includes('/payment-proofs/')){const path=url.split('/payment-proofs/')[1]; if(path){try{await supabase.storage.from('payment-proofs').remove([decodeURIComponent(path)])}catch{}}} await supabase.from('orders').update({payment_proof_url:null}).eq('id',orderId); res.json({message:'Deleted'}) } catch(e){res.status(500).json({error:e.message})} })
app.get('/api/orders/:id/edit-logs', authenticate, async (req, res) => { try { const{data}=await supabase.from('order_edit_history').select('*').eq('order_id',parseInt(req.params.id)).order('created_at',{ascending:false}); res.json(data||[]) } catch(e){res.status(500).json({error:e.message})} })

module.exports = app
